import type { Metadata } from "next";
import { Spectral } from "next/font/google";
import "./globals.css";

const spectralSans = Spectral({
  variable: "--font-spectral",
  subsets: ["latin"],
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${spectralSans.variable} antialiased`}
      >
        {children}
        <footer className="h-10">
          
        </footer>
      </body>
    </html>
  );
}
